import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";
import { Header } from "@/components/layout/header";
import Script from "next/script";
import { FloatingSplineFollower } from "@/components/shared/floating-spline-follower";
import { Footer } from "@/components/layout/footer";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased overflow-x-hidden scrollbar-hide")}>
                <Script src="https://unpkg.com/@splinetool/viewer@latest/build/spline-viewer.js" strategy="afterInteractive" />
                <RouteProvider>
                    <Theme>
                        <div className="fixed inset-0 z-0 pointer-events-none">
                            <video
                                aria-hidden="true"
                                className="absolute inset-0 h-full w-full object-cover"
                                src="/bg2.mp4"
                                playsInline
                                muted
                                loop
                                autoPlay
                                preload="auto"
                            />
                            <div
                                className="absolute inset-0"
                                style={{
                                    background: "linear-gradient(180deg, rgba(7,9,14,0.78) 0%, rgba(10,13,18,0.86) 55%, rgba(0,0,0,0.92) 100%)",
                                }}
                            />
                          
                            <div
                                className="absolute left-0 top-0 h-[50vh] w-[50vw] blur-3xl opacity-30"
                                style={{
                                    background:
                                        "radial-gradient(circle at 30% 30%, rgba(139,92,246,0.22) 0%, rgba(127,86,217,0.12) 35%, rgba(127,86,217,0) 65%)",
                                }}
                            />
                            <div
                                className="absolute right-0 bottom-8 h-[55vh] w-[55vw] blur-3xl opacity-25"
                                style={{
                                    background:
                                        "radial-gradient(circle at 70% 70%, rgba(127,86,217,0.22) 0%, rgba(68,76,231,0.12) 35%, rgba(68,76,231,0) 65%)",
                                }}
                            />
                            <div
                                className="absolute inset-x-0 top-1/2 h-[30vh] -translate-y-1/2 blur-2xl opacity-12"
                                style={{
                                    background:
                                        "linear-gradient(to right, rgba(158,119,237,0.12), rgba(127,86,217,0.06), rgba(158,119,237,0.12))",
                                }}
                            />
                            <div
                                className="absolute inset-0 opacity-35"
                                style={{
                                    background:
                                        "radial-gradient(120% 120% at 50% 50%, rgba(0,0,0,0) 60%, rgba(0,0,0,0.35) 100%)",
                                }}
                            />
                        </div>
                        <FloatingSplineFollower />
                        <div className="relative z-10 min-h-dvh flex flex-col">
                            <Header />
                            <div className="flex-1">{children}</div>
                            <Footer />
                        </div>
                    </Theme>
                </RouteProvider>
            </body>
        </html>
    );
}
